# Generated by Django 5.0.7 on 2024-08-03 01:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import rounds.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("slug", models.SlugField(blank=True, verbose_name="slug")),
                (
                    "number_of_players",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            rounds.validators.EvenValidator(),
                        ],
                        verbose_name="number_of_players",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="tournaments.tournament",
                        verbose_name="tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "round",
                "verbose_name_plural": "rounds",
                "ordering": ("-number_of_players",),
            },
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("tournament", "number_of_players"),
                name="unique_tournament_players",
            ),
        ),
    ]
