services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: twistserve
      POSTGRES_PASSWORD: twistserve
      POSTGRES_DB: twistserve

  rabbitmq:
    image: rabbitmq:3.13
    environment:
      RABBITMQ_DEFAULT_USER: twistserve
      RABBITMQ_DEFAULT_PASS: twistserve

  mailhog:
    image: mailhog/mailhog:v1.0.1

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "celery --app django worker --pool solo"
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - mailhog

  redis:
    image: redis:7.2.5

  django:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - redis
      - postgres
      - mailhog
