# Generated by Django 5.0.7 on 2024-07-26 16:42

import django.db.models.deletion
from django.db import migrations, models

import tournaments.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("players", "0004_alter_player_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("name", models.TextField(verbose_name="name")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=tournaments.models._get_tournament_avatar_dest_path,
                        verbose_name="avatar",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "winner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="titles",
                        to="players.player",
                        verbose_name="winner",
                    ),
                ),
            ],
            options={
                "verbose_name": "tournament",
                "verbose_name_plural": "tournaments",
            },
        ),
    ]
