# Generated by Django 5.0.7 on 2024-08-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="complement",
            field=models.TextField(blank=True, default="", verbose_name="complement"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tournament",
            name="neighborhood",
            field=models.TextField(blank=True, default="", verbose_name="neighborhood"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tournament",
            name="state_province",
            field=models.TextField(blank=True, verbose_name="state/province"),
        ),
    ]
