# Generated by Django 5.0.7 on 2024-07-30 21:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("players", "0001_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("observation", models.TextField(verbose_name="observation")),
                ("date", models.DateField(verbose_name="date")),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="matches_as_player1",
                        to="players.player",
                        verbose_name="player 1",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="matches_as_player2",
                        to="players.player",
                        verbose_name="player 2",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.tournament",
                        verbose_name="tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "match",
                "verbose_name_plural": "matches",
            },
        ),
        migrations.CreateModel(
            name="MatchSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("position", models.PositiveIntegerField(verbose_name="position")),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sets",
                        to="matches.match",
                        verbose_name="set",
                    ),
                ),
            ],
            options={
                "verbose_name": "set",
                "verbose_name_plural": "sets",
            },
        ),
        migrations.CreateModel(
            name="MatchGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="position",
                    ),
                ),
                (
                    "player1_points",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "love"),
                            (15, "15"),
                            (30, "30"),
                            (40, "40"),
                            (9223372036854775807, "game"),
                        ],
                        verbose_name="points won by the player 1",
                    ),
                ),
                (
                    "player2_points",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "love"),
                            (15, "15"),
                            (30, "30"),
                            (40, "40"),
                            (9223372036854775807, "game"),
                        ],
                        verbose_name="points won by the player 2",
                    ),
                ),
                (
                    "game_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="games",
                        to="matches.matchset",
                        verbose_name="set",
                    ),
                ),
            ],
            options={
                "verbose_name": "game",
                "verbose_name_plural": "games",
            },
        ),
        migrations.AddConstraint(
            model_name="matchset",
            constraint=models.UniqueConstraint(
                fields=("position", "match"), name="unique_position_match"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchgame",
            constraint=models.UniqueConstraint(
                fields=("position", "game_set"), name="unique_position_set"
            ),
        ),
    ]
