# Generated by Django 5.0.7 on 2024-08-03 01:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("players", "0001_initial"),
        ("rounds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="observation"),
                ),
                (
                    "match_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="matches",
                        to="rounds.round",
                        verbose_name="round",
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="matches_as_player1",
                        to="players.player",
                        verbose_name="player 1",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="matches_as_player2",
                        to="players.player",
                        verbose_name="player 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "match",
                "verbose_name_plural": "matches",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="Match2MatchRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("player1", "player 1"), ("player2", "player 2")],
                        max_length=8,
                        verbose_name="position",
                    ),
                ),
                (
                    "next_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_match_relationships",
                        to="matches.match",
                    ),
                ),
                (
                    "previous_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_match_relationships",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "match",
                "verbose_name_plural": "matches",
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="MatchSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="position",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sets",
                        to="matches.match",
                        verbose_name="set",
                    ),
                ),
            ],
            options={
                "verbose_name": "set",
                "verbose_name_plural": "sets",
            },
        ),
        migrations.CreateModel(
            name="MatchGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="position",
                    ),
                ),
                (
                    "player1_points",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "love"),
                            (15, "15"),
                            (30, "30"),
                            (40, "40"),
                            (32767, "game"),
                        ],
                        verbose_name="points won by the player 1",
                    ),
                ),
                (
                    "player2_points",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "love"),
                            (15, "15"),
                            (30, "30"),
                            (40, "40"),
                            (32767, "game"),
                        ],
                        verbose_name="points won by the player 2",
                    ),
                ),
                (
                    "game_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="games",
                        to="matches.matchset",
                        verbose_name="set",
                    ),
                ),
            ],
            options={
                "verbose_name": "game",
                "verbose_name_plural": "games",
            },
        ),
        migrations.AddConstraint(
            model_name="match2matchrelationship",
            constraint=models.UniqueConstraint(
                fields=("position", "previous_match", "next_match"),
                name="unique_position_prev_next",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchset",
            constraint=models.UniqueConstraint(
                fields=("position", "match"), name="unique_position_match"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchgame",
            constraint=models.UniqueConstraint(
                fields=("position", "game_set"), name="unique_position_set"
            ),
        ),
    ]
