# Generated by Django 5.0.7 on 2024-07-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matches", "0001_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.tournament",
                verbose_name="tournament",
            ),
        ),
        migrations.AddField(
            model_name="matchset",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sets",
                to="matches.match",
                verbose_name="set",
            ),
        ),
        migrations.AddField(
            model_name="matchgame",
            name="game_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="games",
                to="matches.matchset",
                verbose_name="set",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchset",
            constraint=models.UniqueConstraint(
                fields=("position", "match"), name="unique_position_match"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchgame",
            constraint=models.UniqueConstraint(
                fields=("position", "game_set"), name="unique_position_set"
            ),
        ),
    ]
