# Generated by Django 5.0.7 on 2024-07-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchgame",
            name="player1_points",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "love"),
                    (15, "15"),
                    (30, "30"),
                    (40, "40"),
                    (32767, "game"),
                ],
                verbose_name="points won by the player 1",
            ),
        ),
        migrations.AlterField(
            model_name="matchgame",
            name="player2_points",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "love"),
                    (15, "15"),
                    (30, "30"),
                    (40, "40"),
                    (32767, "game"),
                ],
                verbose_name="points won by the player 2",
            ),
        ),
    ]
