# Generated by Django 5.0.7 on 2024-07-30 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import players.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=players.models._get_player_avatar_dest_path,
                        verbose_name="avatar",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                ("hometown_country", models.TextField(verbose_name="hometown country")),
                (
                    "hometown_state_province",
                    models.TextField(verbose_name="hometown state/province"),
                ),
                ("hometown_city", models.TextField(verbose_name="hometown city")),
                (
                    "weight",
                    models.IntegerField(
                        help_text="player's weight in kilograms",
                        verbose_name="weight (kg)",
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        help_text="player's height in centimeters",
                        verbose_name="height (cm)",
                    ),
                ),
                (
                    "best_hand",
                    models.CharField(
                        choices=[
                            ("left-handed", "left-handed"),
                            ("right-handed", "right-handed"),
                        ],
                        max_length=13,
                        verbose_name="best hand",
                    ),
                ),
                (
                    "backhand",
                    models.CharField(
                        choices=[
                            ("one-handed", "one-handed"),
                            ("two-handed", "two-handed"),
                        ],
                        max_length=20,
                        verbose_name="backhand",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "player",
                "verbose_name_plural": "players",
            },
        ),
    ]
