# Generated by Django 5.0.7 on 2024-07-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
    ]
