# Generated by Django 5.0.7 on 2024-08-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="hometown_state_province",
            field=models.TextField(blank=True, verbose_name="hometown state/province"),
        ),
    ]
