# Generated by Django 5.0.7 on 2024-07-26 03:44

from django.db import migrations, models

import players.models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_alter_player_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="avatar",
            field=models.ImageField(
                null=True,
                upload_to=players.models._get_player_avatar_dest_path,
                verbose_name="avatar",
            ),
        ),
    ]
