# Generated by Django 5.0.7 on 2024-07-26 03:46

from django.db import migrations, models

import players.models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0003_alter_player_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=players.models._get_player_avatar_dest_path,
                verbose_name="avatar",
            ),
        ),
    ]
