# Generated by Django 5.0.7 on 2024-07-27 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0004_alter_player_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="born",
        ),
        migrations.AddField(
            model_name="player",
            name="date_of_birth",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="date of birth"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="backhand",
            field=models.CharField(
                choices=[("one-handed", "one-handed"), ("two-handed", "two-handed")],
                max_length=20,
                verbose_name="backhand",
            ),
        ),
    ]
