# Generated by Django 5.0.7 on 2024-07-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0005_remove_player_born_player_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="hometown",
        ),
        migrations.AddField(
            model_name="player",
            name="hometown_city",
            field=models.TextField(default="unknown", verbose_name="hometown city"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="hometown_country",
            field=models.TextField(default="unknown", verbose_name="hometown country"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="hometown_state_province",
            field=models.TextField(
                default="unknown", verbose_name="hometown state/province"
            ),
            preserve_default=False,
        ),
    ]
