# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Back-End CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CACHE_URL: ${{ secrets.CACHE_URL }}
      CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EMAIL_URL: ${{ secrets.EMAIL_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Build docker compose
        run: |
          docker compose -f docker-compose.test.yml build
          docker compose -f docker-compose.test.yml pull
      - name: Run linter
        run: |
          docker compose -f docker-compose.test.yml run django sh -c \
            "./scripts/lint.sh"
      - name: Run linter
        run: |
          docker compose -f docker-compose.test.yml run django sh -c \
            "python manage.py test"
