name: Back-End CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Build docker compose
        run: |
          docker compose -f docker-compose.test.yml build
          docker compose -f docker-compose.test.yml pull
      - name: Lint
        run: |
          docker compose -f docker-compose.test.yml run \
            --env CACHE_URL=${{ secrets.CACHE_URL }} \
            --env CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }} \
            --env DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --env EMAIL_URL=${{ secrets.EMAIL_URL }} \
            --env SECRET_KEY=${{ secrets.SECRET_KEY }} \
            django sh -c "python ./scripts/test_db_con.py && ./scripts/lint.sh"
      - name: Test
        run: |
          docker compose -f docker-compose.test.yml run \
            --env CACHE_URL=${{ secrets.CACHE_URL }} \
            --env CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }} \
            --env DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --env EMAIL_URL=${{ secrets.EMAIL_URL }} \
            --env SECRET_KEY=${{ secrets.SECRET_KEY }} \
            django sh -c "python ./scripts/test_db_con.py && python manage.py test"